Repository you06/tiedb, pull requests merged in 2020-03, with the labels that each got.

#1 play music when TieDB starts
  scripts/music.sh
Labels: contribution, status/can-merge

#3 Add benchmark doc
  README.md
  docs/benchmark.md
Labels: status/can-merge

#4 Bugfix: create music-down.sh
  scripts/music-down.sh
Labels: contribution, needs-cherry-pick-1.0, status/can-merge
